### ISSUE TITLE
Setup Sonar

### ISSUE THREAD

**Issue by dargzero** [BME-MIT-IET/Element-iet-2018#2]

**Comment by Knozso** [comment]
Akkor a Sonart megcsinálod majd te? Mert akkor én nekiállok a manuális kód átvizsgálásnak és a Deployment segítésének.

**Comment by dargzero** [comment]
Hello
Sonar már be van lőve. Elvileg a főoldalon levő Badge-ről elérhető.
( https://sonarcloud.io/dashboard?id=tr.com.srdc%3Aontmalizer [https://sonarcloud.io/dashboard?id=tr.com.srdc%3Aontmalizer] )



On Sun, Apr 29, 2018 at 13:29, Knozso <notifications@github.com> wrote:
Akkor a Sonart megcsinálod majd te? Mert akkor én nekiállok a manuális kód átvizsgálásnak és a Deployment segítésének.
